api:
  port: 8082
serviceDiscovery:
  consul:
    address: http://consul:8500
messenger:
  kafka:
    Address: kafka
    Port: 9092
database:
  mysql:
    user: root
    password: password
    db_name: mvdb
    host: db
    port: 3306