apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata
          image: mwg-registry:5000/metadata:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081