version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: mwg-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: mwg-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  consul:
    image: hashicorp/consul:latest
    container_name: mwg-consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server   -ui   -node=server-1   -bootstrap-expect=1   -client='0.0.0.0'

  db:
    image: mysql:latest
    container_name: mwg-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mvdb