api:
  port: 8081
serviceDiscovery:
  consul:
    address: http://localhost:8500
database:
  mysql:
    user: root
    password: password
    db_name: mvdb
    host: localhost
    port: 3306
jaeger:
  url: http://localhost:14268/api/traces
