api:
  port: 8081
serviceDiscovery:
  consul:
    address: http://consul:8500
database:
  mysql:
    user: root
    password: password
    db_name: mvdb
    host: db
    port: 3306
jaeger:
  url: http://jaeger:4318/v1/traces
prometheus:
  metricsPort: 8091
